### ISSUE TITLE
MethodNotAllowedHttpException on users_mass_destroy

### ISSUE THREAD

**Issue by SturmB** [LaravelDaily/laravel-roles-permissions-bouncer#2]
I've done some minor modifications to AdminLTE (including applying a purchased admin template rather than AdminLTE) and now I am unable to mass-delete users. Instead, I receive a `MethodNotAllowedHttpException in RouteCollection.php (line 251)`. What pieces need to be in place so that mass delete button will work?

Also, please forgive me for being a complete newbie to AdminLTE and Bouncer, as well as a still-learning rookie with Laravel.

**Comment by PovilasKorop** [comment]
@SturmB our mass-delete functionality is located in every index.blade.php file, like this:

```
@can('project_delete')
  @if ( request('show_deleted') != 1 ) window.route_mass_crud_entries_destroy = '{{ route('admin.projects.mass_destroy') }}'; @endif
@endcan
```

Then in your `routes/web.php` file you should have something like this:
```
Route::post('projects_mass_destroy', ['uses' => 'Admin\ProjectsController@massDestroy', 'as' => 'projects.mass_destroy']);
```

Not sure which part you have changed/deleted, but I hope these tips will help.

**Comment by SturmB** [comment]
That's a little different from the equivalent files shown in this repo, but essentially the same. I'll try cloning a fresh copy from this repo and seeing how it works without changing anything, but I'm pretty sure I haven't changed much. If you have the time and inclination, please feel free to have a quick look at [my project](https://github.com/SturmB/sky-schedule) and I'm sure you will be able to spot the problem long before I can.

Again, I am sorry for being such a pain about this. I'm doing the best I can to learn this in the relatively short time frame I was given. Thank you.

**Comment by PovilasKorop** [comment]
@SturmB sorry, my example wasn't from this exact repo, rather from our general QuickAdminPanel generator.

I've looked at your repo and it seems that you've changed the structure of how JavaScript is loaded. 

So in file `resources/views/admin/users/index.blade.php` instead of our `@section('javascript')` you now have `@push('scripts_bottom')` so now I cannot easily understand how those scripts are loaded, I would guess that it's not in a correct order, so mass-delete functionality doesn't "catch" that mass-delete route variable.

I'm afraid that's all I can help you in 5-minute time I have, without actually installing your project and debugging. Sorry, our tool is aimed at Laravel developers (with purpose to save their time), not so much for learners.

**Comment by SturmB** [comment]
> I would guess that it's not in a correct order, so mass-delete functionality doesn't "catch" that mass-delete route variable.

Bingo.

Actually, it pointed me in the right direction. There were probably two issues at play (not sure if the first is as important as the second):
1. The `window.route_mass_crud_entries_destroy = '{{ route('users.mass_destroy') }}';` script line was not being called *last*
2. I had neglected to include the `window._token = '{{ csrf_token() }}';` script line before it.

As far as the `@push…@endpush` and their corresponding `@stack` directives go, they pretty much work very similar to the `@section…@endsection` and their corresponding `@yield` directives. From what I learned when reading [the docs](https://laravel.com/docs/5.4/blade#stacks), the only difference is that `@push` blocks *add* to a `@stack` area, whereas `@section` blocks *replace* whatever was previously in the same-named `@yield` area. Thus, `@push/@stack` is more ideal for css and javascript includes, especially if you have many nested blade templates with each one calling for their own css/js files.

Anyway, thank you so much for making this awesome starter template for bouncer! It has greatly helped and given me a much-needed head start on my project! (Feel free to close this issue.)
