### ISSUE TITLE
Parmission Edit error????

### ISSUE THREAD

**Issue by wapshekhar** [LaravelDaily/laravel-roles-permissions-bouncer#4]
If we have edit permission name after assign to a user then i got error because you directly check permission name on view like  @can('users_manage') it is not dynamic method

i'm noob in laravel sorry for if i missing some thing

**Comment by PovilasKorop** [comment]
@wapshekhar well, yes, you're right - this panel was created to manage permissions, like their names, but it doesn't automatically handle the logic of USING the permissions in your app. So if you changed the name of permission - then yes, in this case, you need to change it everywhere in your codebase, I'm afraid.
